### ISSUE TITLE
Broadcasting in Ska.quatutil.yagzag2radec 

### ISSUE THREAD

**Issue by javierggt** [sot/Ska.quatutil#13] opened 2020-09-03 18:27 UTC
This issue follows issue sot/chandra_aca/issues/102 and it is better described there.

**Comment by taldcroft** [comment] 2020-09-13 14:05
I have a fix for this which I believe works. Part of the problem is that we (I?) have chosen the wrong convention for where to place the extra axes in places (e.g. `eci2radec`). These extra axes were put at the end of the shape, which can make life easier if there is just a single extra axis, but for multiple extra axes I think that breaks down. For Quaternion @javierggt got it right.

```
def yagzag2radec(yag, zag, q):
    """
    Given ACA Y-ang, Z-ang and pointing quaternion determine RA, Dec. The
    input ``yag`` and ``zag`` values can be 1-d arrays in which case the output
    ``ra`` and ``dec`` will be corresponding arrays of the same length.

    :param yag: ACA Y angle (degrees)
    :param zag: ACA Z angle (degrees)
    :param q: Quaternion
    :rtype: list ra, dec (degrees)
    """
    try:
        one = np.ones(len(yag))
    except TypeError:
        one = 1.0
    d_aca = np.array([one, tan(radians(yag)), tan(radians(zag))])
    d_aca *= 1.0 / np.sum(d_aca**2)
    d_aca_t = np.moveaxis(d_aca, 0, -1)
    eci = np.einsum('...jk,...k->...j', q.transform, d_aca_t)
    eci_t = np.moveaxis(eci, 0, -1)
    return eci2radec(eci_t)

```

**Comment by taldcroft** [comment] 2020-09-13 14:12
One idea that just occurred to me is to basically stop updating Ska.quatutil and copy the functionality we need into Quaternion or chandra_aca.transform, and then make the N-d support work consistently. We could perhaps deprecate Ska.quatutil, but that is not necessarily needed.

**Comment by javierggt** [comment] 2020-09-13 14:50
I second this last proposal. I would split it: radec2yagzag and yagzag2radec into chandra_aca.transform, the rest into Quaternion.

**Comment by jeanconn** [comment] 2020-09-13 15:30
I may not understand scope, but I was thinking we might want to do something in Ska.quatutil to have those methods just *not support* a Quaternion with length > 1 and raise an error.  That would at least be consistent.   If we are moving methods around, we may still want something like that and a deprecation warning.

**Comment by javierggt** [comment] 2020-09-14 13:06
well, I think there is not much difference whether we make it work with the vectorized quaternion before or after deprecating and moving.

**Closed** 2020-09-24 10:05 UTC
